### ISSUE TITLE
Fastboot error: TypeError: _ember.default.$ is not a function

### ISSUE THREAD

**Issue by pgrippi** [tim-evans/ember-page-title#51]
This is caused by #50 

jQuery is not available in the Fastboot environment as they use a simplified DOM npm package for rendering in node. Specifically it fails on this line: [app/initializers/page-title-setup.js:8](https://github.com/tim-evans/ember-page-title/blob/master/app/initializers/page-title-setup.js#L8)

**Comment by tim-evans** [comment]
Thanks for reporting this- will have a release out soon to fix this.

**Comment by tim-evans** [comment]
Released 3.1.4- could you confirm that this works with fastboot?

**Comment by pgrippi** [comment]
Sadly it's still not working, the error is now: `Unknown Error: ReferenceError: document is not defined`

**Comment by pgrippi** [comment]
@tim-evans I have come up with a prototype but it's far from complete.

Ember has an internal `-document` service that in the browser returns the top level `document` object and in node returns the simple-dom object. The first problem is that you have to convert this to an instance initializer so that you can use `application.lookup` to find it.

The second problem is because of the first: since the application has boot at this point the `<title>` tag inserted by this addon is in the dom, so there are already two title tags. So then this initializer will remove both, resulting in no `<title>` tags in the DOM.

Here is the instance-initializer I came up with, I borrowed all the logic from [ember-wormhole's dom util](https://github.com/yapplabs/ember-wormhole/blob/978812f1d419a2fa55fcaf7e9f350dddf00a0724/addon/utils/dom.js).

```js
import Ember from 'ember';

export default {
  name: 'page-title-setup',
  initialize(application) {
    // Remove <title> tags from the initial index.html page, so they can be correctly replaced
    // and managed by ember-cli-head.
    let titles = getElementsByTagName(getDom(application), 'title');
    for (let i = 0; i < titles.length; i++) {
      let title = titles[i];
      title.parentNode.removeChild(title);
    }
  }
};

function getDom(application) {
  let documentService = application.lookup('service:-document');
  if (documentService) {
    return documentService;
  }

  let renderer = container.lookup('renderer:-dom');
  if (renderer._dom && renderer._dom.document) { // pre Ember 2.6
    return renderer._dom.document;
  } else {
    throw new Error('ember-page-title could not get DOM');
  }
}

function getElementsByTagName(doc, tagName) {
  if (doc.getElementsByTagName) {
    return doc.getElementsByTagName(tagName);
  }

  tagName = tagName.toUpperCase();

  let node;
  let nodes = childNodesOfElement(doc);
  let matchedNodes = [];

  while (nodes.length) {
    node = nodes.shift();

    if (node.tagName === tagName) {
      matchedNodes.push(node);
    }

    nodes = childNodesOfElement(node).concat(nodes);
  }

  return matchedNodes;
}

function childNodesOfElement(element) {
  let children = [];
  let child = element.firstChild;
  while (child) {
    children.push(child);
    child = child.nextSibling;
  }
  return children;
}
```

**Comment by tim-evans** [comment]
Could you write a PR?

**Comment by evoactivity** [comment]
Literally just ran into this setting up a new project, when I use your initializer @pgrippi I get

```
Unknown Error: TypeError: application.lookup is not a function
```

**Comment by pgrippi** [comment]
I am working on a PR now that addresses the issues I've found, should posted it up soon

**Comment by fotinakis** [comment]
I think the absolute easiest fix here is to just recommend that fastboot apps remove the `<title>` tag like normal, and make the current initializer only run with a conditional like `if (Ember.$) { Ember.$('title').remove() }` — happy to add that and update the readme if that sounds good @tim-evans .

**Comment by pgrippi** [comment]
After more playing around with this I'm not sure it's possible to remove the title in fastboot. It appears the order of operations is something like this:

Fastboot creates simple-dom > fastboot renders ember app into html > fastboot then puts that html into the `index.html` file and serves it to the browser

Because that's the order there is no code we can write in an instance initializer that could find the html and remove it. I think the best solution for now is the one proposed by @fotinakis, until fastboot becomes more extendable and allows for us to write hooks for pre/post rendering.

Also to address your issue @evoactivity you have to put `before: 'head-fastboot'` into the initializer otherwise it runs afterwards and removes the title added by ember-cli-head.

**Comment by evoactivity** [comment]
I updated my instance-initializer to the one in your PR @pgrippi and now we're back to `document is not defined` while @fotinakis PR did work for me.

**Comment by pgrippi** [comment]
@evoactivity did you put your instance-initializer in a `browser` folder (i.e., `app/instance-initializers/browser/file.js`)? Otherwise it will execute in both environments and will break in fastboot mode

**Comment by evoactivity** [comment]
@pgrippi silly me, didn't notice that in the PR. Works just fine.

**Comment by tim-evans** [comment]
Is this resolved now?

**Comment by fotinakis** [comment]
Yes, resolved with #52. 👍

**Comment by tim-evans** [comment]
Super 👍
